image-job:
  stage: build
  only:
    changes:
      - docker/*
  script:
    - echo "build Image start"
    - cd docker
    - docker build -t plcn .
    - echo "build image success!"

solution-job:
  stage: build
  only:
    - main
  script:
    - echo "build sln start"
    - docker rm -f plcn
    - docker run -it --rm -d --name plcn -v "$(pwd):C:\solution" plcn
    - docker exec plcn powershell C:\minVS\MSBuild\Current\bin\MSbuild.exe c:\solution\IIoT_Library.sln
    - echo "MSbuild vsproject success!"

test-job:
  stage: test
  script:
    - echo "test"

deploy-job:
  stage: deploy
  script:
    - echo "deploy"
