solution-job:
  stage: build
  only:
    - main
  artifacts:
    paths:
      - Cli/*.pcwlx
      - Impl/Release/*.log
  image: plcn:latest
  script:
    - echo "build sln start"
    - C:\minVS\MSBuild\Current\bin\MSbuild.exe IIoT_Library.sln
    - echo "build sln success"

