stages:
  - build
  - packages

default:
  image: plcn:latest
  cache:
    paths:
      - Cli/*.pcwlx
      - Impl/Release/*.log

build-project-job:
  stage: build
  script:
    - echo "build sln start"
    - msbuild IIoT_Library.sln
    - echo "build sln success"

package-upload-job:
  stage: packages
  artifacts:
    paths:
      - Cli/*.pcwlx
      - Impl/Release/*.log
  script:
      - echo "upload build project and logs"
