stages:
  - build
  - packages

image: plcn:latest

cache:
  paths:
    - Cli/*.pcwlx
    - Impl/Release/*.log

build-project-job:
  stage: build
  only:
    - main
  script:
    - echo "build sln start"
    - msbuild IIoT_Library.sln
    - echo "build sln success"

package-upload-job:
  stage: packages
  only:
    - main
  artifacts:
    paths:
      - Cli/*.pcwlx
      - Impl/Release/*.log
  script:
      - echo "upload build project and logs"


