solution-job:
  stage: build
  only:
    - main
  artifacts:
    paths:
      - Cli/*.pcwlx
      - build.log
  image: plcn:latest
  script:
    - echo "build sln start"
    - C:\minVS\MSBuild\Current\bin\MSbuild.exe IIoT_Library.sln | Out-File build.log
    - echo "build sln success"

