# gitlab-runner configure

concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "plcn_image"
  url = "http://43.154.144.20/"
  token = "WkFPnbDUPxshtEZamN46"
  executor = "shell"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "plcn_build"
  url = "http://43.154.150.20/"
  token = "hv4iLf2qPb1e5SghCLfv"
  executor = "docker-windows"
  shell = "powershell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    privileged = false
    image = "mcr.microsoft.com/windows/servercore:ltsc2019"
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["c:\\cache"]
    shm_size = 0
