stages:
  - build
  - tag
  - push-image

image-all-job:
  stage: build
  only:
    changes:
      - packages/*
      - dockerfile
      - .gitlab-ci.yml
  script:
    - echo "build Image start"
    - docker build -t plcn:latest .
    - echo "build image success"

image-tag-job:
  stage: tag
  only:
    - tags
  script:
    - echo "build Image start"
    - docker build -t plcn:latest .
    - docker build -t plcn:"$CI_COMMIT_REF_NAME" .
    - echo "build image success"

push-image-job:
  stage: push-image
  only:
    - tags
  script:
    - echo "push Image plcn:$CI_COMMIT_REF_NAME start"
    - echo "push image success"
