image-all-job:
  stage: build
  only:
    changes:
      - packages/*
      - dockerfile
      - .gitlab-ci.yml
  script:
    - echo "build Image start"
    - docker build -t plcn:latest .
    - echo "build image success"


image-tag-job:
  stage: build
  only:
    - tags
  script:
    - echo "build Image start"
    - docker build -t plcn:latest .
    - docker build -t plcn:"$CI_COMMIT_REF_NAME" .
    - echo "build image success"