image-job:
  stage: build
  only:
    changes:
      - packages/*
      - dockerfile
  script:
    - echo "build Image start"
    - docker build -t plcn .
    - echo "build image success"

test-job:
  stage: test
  script:
    - echo "test"

deploy-job:
  stage: deploy
  script:
    - echo "deploy"
